### ISSUE TITLE
Add SNMP protocol

### ISSUE THREAD

**Issue by alegrey91** [echo-devim/inou#1]
Hi @echo-devim. I think could be interesting to add also the SNMP protocol.
If you want I can take care of it. Let me know. ;)

**Comment by echo-devim** [comment]
SNMP actually isn't my priority, thus if you want to contribute you're welcome :)

The next protocols I'm going to add are the following:
*  DNS
*  RabbitMQ
*  NTP
*  Detect common serialization/deserialization techniques

**Comment by alegrey91** [comment]
Ok! I'll send you the pull request asap.

**Comment by echo-devim** [comment]
Solved with #2
